# location = /files { return 301 /files/; }

# Serve /files/... from /var/lib/nginx/html/...
location /files/ {
  alias /var/lib/nginx/html/files/;   # note the trailing slash
  index index.html;
}


