server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;  # Change to your proxy server domain
    
    # SSL configuration for the proxy server
    ssl_certificate /etc/ssl/certs/nginx.crt;  # Path to your SSL certificate
    ssl_certificate_key /etc/ssl/private/nginx.key;  # Path to your SSL private key

    include /etc/nginx/http.d/*.conf

}
