# Exact "/" landing page
location = / {
  default_type text/html;
  return 200 '
<!doctype html>
<html>
<head><meta charset="utf-8"><title>nginx Container: Static Example</title></head>
<body>
  <h1>nginx on $host</h1>
  <ul>
    <li><a href="/static/">Static Example</a></li>
  </ul>
</body>
</html>';
}

# Files area
# Redirect "/static" -> "/static/"
location = /static{ return 301 /static/; }

location /static/ {
  alias /var/lib/nginx/html/static/;  # keep trailing slash
  index index.html;
}

